#!/usr/bin/env python
import sys
import socket

def main(args):
    if len(args) != 3:
        return -1

    host = str(args[1])
    port = int(args[2])

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    #s = socket.socket()
    print "CONNECTING..."
    s.connect((host, port))
    #s.send("GET / HTTP/1.0\r\n\r\n")
    #while 1:
    #    buf = s.recv(1000)
    #    if not buf:
    #        break
    #    sys.stdout.write(buf)
    
    print 'got:'
    print s.recv(1024)
    print 'and next:'
    print s.recv(1024)
    print "done."
    s.close()

# run the 'main()' function if this script is run from the command line;
# this will not execute if the file is imported.
#
# pass in command line arguments verbatim, as a list.

if __name__ == '__main__':
    exit_code = main(sys.argv)
    sys.exit(exit_code)

